// Profile
export const INJECT_PROFILE = 'INJECT_PROFILE'

// Role
export const INJECT_ROLE = 'INJECT_ROLE'

// Project List
export const SET_PROJECT_LIST = 'SET_PROJECT_LIST'

// Install Status
export const SET_SIGNUP_STATUS = 'SET_SIGNUP_STATUS'

// Sidebar
export const SET_SIDEBAR_STATUS = 'SET_SIDEBAR_STATUS'

// Service
export const QUERY_SERVICE_MODULE = 'QUERY_SERVICE_MODULE'

export const RESET_SERVICE_MODULE = 'RESET_SERVICE_MODULE'

export const QUERY_SERVICE_LIST = 'QUERY_SERVICE_LIST'

export const OPEN_SHOW_NEXT = 'OPEN_SHOW_NEXT'

export const SERVICE_DIALOG_VISIBLE = 'SERVICE_DIALOG_VISIBLE'

export const CURRENT_SERVICE = 'CURRENT_SERVICE'

export const CHART_NAMES = 'CHART_NAMES'

export const RESET_CHART_NAMES = 'RESET_CHART_NAMES'

export const UPDATE_ENV_BUTTON = 'UPDATE_ENV_BUTTON'

export const QUERY_ORDER_SERVICE = 'QUERY_ORDER_SERVICE'

// External Link
export const SET_EXTERNAL_LINK = 'SET_EXTERNAL_LINK'

// Common Workflow
export const UPDATE_TABS = 'UPDATE_TABS'

export const UPDATE_COMMON_INFO = 'UPDATE_COMMON_INFO'

export const RESET_COMMON_WORKFLOW = 'RESET_COMMON_WORKFLOW'
